baseurl = "https://www.facebook.com/DuongHoaiAn"
title = "DHA page"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  [[params.navlinks]]
  name = "About me/"
  url = "about/"

  [[params.navlinks]]
  name = "Education/"
  url = "photos/"
  
  [[params.navlinks]]
  name = "Experience/"
  url = "posts/"
